sonar.projectKey=JulienForestier_CESI-CI-CD
sonar.organization=julienforestier

sonar.sources=application/collector-shop/src,api/CESI-CI-CD
sonar.tests=application/collector-shop/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/bin/**,**/obj/**,**/coverage/**

sonar.javascript.lcov.reportPaths=application/collector-shop/coverage/lcov.info
