sonar.projectKey=JulienForestier_CESI-CI-CD
sonar.organization=julienforestier

sonar.sources=application/collector-shop/src,api/CESI-CI-CD,api/CESI-CI-CD.ApiService
sonar.tests=application/collector-shop/src,api/CESI-CI-CD.ApiService.Tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,api/CESI-CI-CD.ApiService.Tests/**/*.cs

sonar.exclusions=**/node_modules/**,**/dist/**,**/bin/**,**/obj/**,**/coverage/**
sonar.coverage.exclusions=**/Migrations/**,api/CESI-CI-CD/**

sonar.javascript.lcov.reportPaths=application/collector-shop/coverage/lcov.info
sonar.cs.opencover.reportsPaths=api/CESI-CI-CD.ApiService.Tests/TestResults/**/coverage.opencover.xml
